# Generated by Django 5.2 on 2025-04-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_profile_user_profile_word_shading_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bright_letters',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='bright_letters_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
